language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug PYTHON=2.7.15
    - CMAKE_BUILD_TYPE=Debug PYTHON=3.6.7
    - CMAKE_BUILD_TYPE=Release PYTHON=2.7.15
    - CMAKE_BUILD_TYPE=Release PYTHON=3.6.7

before_install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-key update; sudo apt-get update; fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/ubuntu.deps.sh; fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/osx.deps.sh; fi

script:
  # iam: need to make sure the shims intercept (osx is the culprit here)
  - source ${HOME}/.bash_profile;
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - make
  - make check
